// src/lib/components/Metronome.svelte
<script>
  import metronomeSFX from '/metronome.mp3';
  import {counter, reps, currentPattern, patterns} from '../store';

  let bpm = 120;
  let playing = false;
  let intervalId;

  // $: downbeat = $counter % 2 === 0;

  const audio = new Audio(metronomeSFX);

  const togglePlaying = () => {
    if (playing) {
      clearInterval(intervalId);
      playing = false;

      setTimeout(() => {
        $counter = 0;
      }, 400);
    } else {
      intervalId = setInterval(() => {
        // if (downbeat) {
        audio.currentTime = 0;
        audio.play();
        // }

        setTimeout(() => {
          if ($counter > 0 && $counter % ($reps * 16) === 0) {
            $currentPattern = ($currentPattern + 1) % $patterns.length;
            $counter = 0;
          }
          $counter += 1;
        }, 300);
      }, (60 / bpm) * 500);

      playing = true;
    }
  };
</script>

<div class="flex justify-center flex-col items-center my-8">
  <label>
    <input
      type="number"
      class="text-black border-black border"
      bind:value={bpm}
    />
    BPM
  </label>

  <div>
    <button
      class="bg-slate-300 py-2 px-4 border-black border-2 text-black my-4 rounded-md"
      on:click={togglePlaying}
    >
      {playing ? 'Stop' : 'Start'}
    </button>
  </div>
</div>

// src/components/Metronome.jsx
import { useState, useEffect } from "react";
import metronomeSFX from "/sfx/metronome.mp3";

const Metronome = () => {
  const [bpm, setBpm] = useState(60);
  const [playing, setPlaying] = useState(false);
  const [intervalId, setIntervalId] = useState();

  const audio = new Audio(metronomeSFX);

  const togglePlaying = () => {
    if (playing) {
      // audio.pause();
      clearInterval(intervalId);
      setPlaying(false);
    } else {
      setIntervalId(
        setInterval(() => {
          audio.currentTime = 0;
          audio.play();
        }, (60 / bpm) * 1000)
      );

      setPlaying(true);
    }
  };

  return (
    <div className="flex justify-center flex-col items-center">
      <div>
        <input
          type="number"
          className="text-black"
          value={bpm}
          onChange={(e) => setBpm(e.target.value)}
        />
        BPM
      </div>
      <div>
        <button
          className="bg-slate-50 py-2 px-4 border text-black my-4"
          onClick={togglePlaying}
        >
          {playing ? "Stop" : "Start"}
        </button>
      </div>
    </div>
  );
};

export default Metronome;
