// src/App.svelte
<script>
  import Footer from './lib/components/Footer.svelte';
  import Instructions from './lib/components/Instructions.svelte';
  import Metronome from './lib/components/Metronome.svelte';
  import Nav from './lib/components/Nav.svelte';
  import Notation from './lib/components/Notation.svelte';
  import NotationPreview from './lib/components/NotationPreview.svelte';

  import {currentPattern} from './lib/store';
</script>

<Nav />
<div
  class="main box-border flex flex-col justify-center my-8 max-w-screen-md m-auto bg-white p-6 border rounded-md shadow-md"
>
  <div class="text-center">
    <h1>Stick Control</h1>
    <h2>for the Snare Drummer</h2>
    <h4>
      <em>... for the Screen</em>
    </h4>
  </div>

  <Metronome />

  {#key $currentPattern}
    <Notation />
    <NotationPreview />
  {/key}

  <Instructions />
</div>
<Footer />

// src/App.jsx
import { useState, useContext, createContext } from "react";
import Metronome from "./components/Metronome";
import Notation from "./components/Notation";

export const CounterContext = createContext(null);

function App() {
  const [bpm, setBpm] = useState(60);
  const [playing, setPlaying] = useState(false);

  const [counter, setCounter] = useState(0);

  const tick = () => setCounter((ct) => ct + 1);

  const resetCounter = () => setCounter(0);

  return (
    <CounterContext.Provider value={{ counter, tick, resetCounter }}>
      <div className="flex flex-col justify-center my-8 max-w-screen-md m-auto">
        <h1 className="text-center text-5xl my-4 underline">Stick Control</h1>
        <h2 className="text-center text-3xl my-1">for the Snare Drummer</h2>
        <h3 className="text-center text-xl my-1">
          <em>... for the Screen</em>
        </h3>
        <Metronome
          bpm={bpm}
          setBpm={setBpm}
          playing={playing}
          setPlaying={setPlaying}
        />
        <Notation />
      </div>
    </CounterContext.Provider>
  );
}

export default App;
